"""add project_id to users

Revision ID: d0784b66e3e7
Revises: f14d54409177
Create Date: 2026-02-01 19:10:13.420170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0784b66e3e7'
down_revision: Union[str, Sequence[str], None] = 'f14d54409177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'project_id')
    # ### end Alembic commands ###
